export const steps = [
    {
        tour: "mainTour",
        steps: [
            {
                icon: "👋",
                title: "Welcome to HireAI",
                content: "Your AI-powered hiring copilot that finds specialized talent in seconds!",
                selector: "#step1",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "🔍",
                title: "Natural Language Search",
                content: "Type queries like 'Find senior Gen-AI engineers with LangChain + RAG experience in Europe' and get instant results.",
                selector: "#search",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "⚡",
                title: "Instant Candidate Matching",
                content: "See ranked, de-duplicated candidates immediately based on your requirements.",
                selector: "#matching",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "📝",
                title: "Automated Resume Parsing",
                content: "Our AI extracts skills and experience from resumes with 99% accuracy.",
                selector: "#parsing",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "🤖",
                title: "AI Pre-Screening",
                content: "Automated background checks and Q&A generation to save you time.",
                selector: "#screening",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "📊",
                title: "Talent Pool Analytics",
                content: "Real-time dashboards showing your talent pipeline metrics and insights.",
                selector: "#analytics",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "✉️",
                title: "Personalized Outreach",
                content: "Launch customized email campaigns to candidates with one click.",
                selector: "#outreach",
                side: "right",
                showControls: true,
                showSkip: true,
            },
            {
                icon: "⚙️",
                title: "Bias Reduction Tools",
                content: "Our AI helps eliminate unconscious bias from your hiring process.",
                selector: "#bias-reduction",
                side: "right",
                showControls: true,
                showSkip: true,
            },
        ],
    },
];