export const demoCandidates = [
    // {
    //     _id: "1",
    //     name: "Sarah Johnson",
    //     email: "sarah.johnson@example.com",
    //     position: "Senior AI Engineer",
    //     skills: ["LangChain", "RAG", "Python", "LLMs"],
    //     status: "pending",
    //     lastContacted: new Date("2025-05-28").toISOString(),
    //     experience: "5+ years in NLP and generative AI",
    //     location: "Berlin, Germany",
    // },
    // {
    //     _id: "2",
    //     name: "Michael Chen",
    //     email: "michael.chen@example.com",
    //     position: "Machine Learning Engineer",
    //     skills: ["TensorFlow", "PyTorch", "Computer Vision"],
    //     status: "contacted",
    //     lastContacted: new Date("2025-05-25").toISOString(),
    //     experience: "4 years in deep learning",
    //     location: "San Francisco, USA",
    // },
    // {
    //     _id: "3",
    //     name: "Emma Rodriguez",
    //     email: "emma.rodriguez@example.com",
    //     position: "AI Research Scientist",
    //     skills: ["LLMs", "Transformers", "NLP"],
    //     status: "pending",
    //     lastContacted: new Date("2025-05-20").toISOString(),
    //     experience: "PhD in Machine Learning",
    //     location: "London, UK",
    // },
    // {
    //     _id: "4",
    //     name: "David Kim",
    //     email: "david.kim@example.com",
    //     position: "MLOps Engineer",
    //     skills: ["AWS", "Kubernetes", "CI/CD"],
    //     status: "accepted",
    //     lastContacted: new Date("2025-05-15").toISOString(),
    //     experience: "3 years in cloud infrastructure",
    //     location: "Seoul, South Korea",
    // },
    // {
    //     _id: "5",
    //     name: "Priya Patel",
    //     email: "priya.patel@example.com",
    //     position: "Data Scientist",
    //     skills: ["Python", "Pandas", "SQL", "Statistics"],
    //     status: "rejected",
    //     lastContacted: new Date("2025-05-10").toISOString(),
    //     experience: "4 years in data analysis",
    //     location: "Bangalore, India",
    // },
    // {
    //     _id: "6",
    //     name: "James Wilson",
    //     email: "james.wilson@example.com",
    //     position: "AI Product Manager",
    //     skills: ["Product Strategy", "Agile", "AI Integration"],
    //     status: "pending",
    //     lastContacted: new Date("2025-05-05").toISOString(),
    //     experience: "6 years in tech product management",
    //     location: "New York, USA",
    // },
];